#!/bin/sh

readonly YAZFI_NAME="YazFi"
readonly YAZFI_VERSION="v3.0.1"
readonly YAZFI_BRANCH="develop"
readonly YAZFI_REPO="https://raw.githubusercontent.com/jackyaz/YazFi/""$YAZFI_BRANCH""/YazFi"

Check_Lock(){
	if [ -f "/tmp/$YAZFI_NAME.lock" ]; then
		exit 1
	else
		echo "$$" > "/tmp/$YAZFI_NAME.lock"
		return 0
	fi
}

Clear_Lock(){
	rm -f "/tmp/$YAZFI_NAME.lock" 2>/dev/null
	return 0
}

Check_Lock
/usr/sbin/curl -fsL --retry 3 "$YAZFI_REPO.sh" -o "/jffs/scripts/$YAZFI_NAME"
chmod 0755 "/jffs/scripts/$YAZFI_NAME"
sleep 5
Clear_Lock
/jffs/scripts/$YAZFI_NAME runnow &
exit 0
