#!/bin/sh
# shellcheck disable=SC2039
trap '' SIGHUP

/jffs/addons/YazFi.d/YazFiMonitor &

while true; do
	sleep 5
	if [ "$(pidof YazFiMonitor | wc -w)" -lt 1 ]; then
		logger -t YazFi "YazFiMonitor dead, restarting..."
		killall -q YazFiMonitor
		sleep 5
		/jffs/addons/YazFi.d/YazFiMonitor &
		logger -t YazFi "YazFiMonitor restarted"
	fi
done
